### ISSUE TITLE
Loosen Controls for Emote Resizing

### ISSUE THREAD

**Issue by intentionallyIncomplete** [intentionallyIncomplete/BadMovieCytube#3]
Current Behavior:

When a user adds an emote or a GIF from GIPHY, the size of the image/video is very small but not cropped.

Expected Behavior:

When a user adds an emote or a GIF from GIPHY, the size of the image is cropped or scaled appropriately but is not less than 50% of the original size.

**Comment by vandrenth** [comment]
the theme uses a list of regular expressions to add extra chat functionality.

The regex in question:

{"name":"giphy","source":"https?://(?|media\\d\\.giphy\\.com/media/([^ /\\n]+)/giphy\\.gif|i\\.giphy\\.com/([^ /\\n]+)\\.gif|giphy\\.com/gifs/(?:.*-)?([^ /\\n]+))","flags":"gi","replace":"<img class=\"giphy chat-picture\" src=\"https://media.giphy.com/media/\\1/200_s.gif\" />","active":true,"filterlinks":true}

I've taken out the part that adds a still image rather than the gif itself, so I'll remove that part from the JS module. Still looking for where it resizes them in the CSS, because 320x200 still should be big enough for most purposes
